In [7]:
import numpy as np
import random

class osero():
    def __init__(self):
        self.n_rows=8
        self.n_cols=8
        self.cells=np.zeros((self.n_rows,self.n_cols))
        self.blank=0
        self.white=1
        self.black=2
        
        self.cells[3][3]=self.white
        self.cells[3][4]=self.black
        self.cells[4][3]=self.black
        self.cells[4][4]=self.white
        
    def flip_able_man(self,now_state,current_player):
        self.now_state=now_state
        self.current_player=current_player
        dir_list=[-1,0,1]
        self.flip_able=[]
        for dx in dir_list:
            for dy in dir_list:
                temp=[]
                depth=0
                while True:
                    depth+=1
                    rx=self.now_state[0]+dx*depth
                    ry=self.now_state[1]+dy*depth
                    
                    if 0<=rx<8 and 0<=ry<8:
                        piece=self.cells[rx][ry]
                        
                        if piece==self.blank:
                            break
                        elif piece==self.current_player:
                            if temp!=[]:
                                self.flip_able.extend(temp)
                        else:
                            temp.append([rx,ry])
                    else:
                        break
        return self.flip_able
    
    def flip(self):
        for i in range(len(self.flip_able)):
            self.cells[self.flip_able[i][0]][self.flip_able[i][1]]=self.current_player
            
        self.cells[self.now_state[0]][self.now_state[1]]=self.current_player
        return self.cells
    
    def show_board(self):
        self.board=[]
        for i in range(self.n_rows):
            for j in range(self.n_cols):
                pi=self.cells[i][j]
                if pi==self.blank:
                    self.board.append('*')
                elif pi==self.white:
                    self.board.append('○')
                else:
                    self.board.append('●')
                    
        self.board=np.array(self.board).reshape(self.n_rows,self.n_cols)
        print(self.board)
        
    def End(self,player):
        self.possible=[]
        for i in range(self.n_rows):
            for j in range(self.n_cols):
                pi=self.cells[i][j]
                if pi!=self.blank:
                    if pi!=player:
                        self.possible.append([i,j])
        if len(self.possible)==0:
            return True
        else:
            return False
        
    def player_change(self,player):
        if player==self.white:
            return self.black
        else:
            return self.white
        
    def winner(self):
        color_white=0
        color_black=0
        for i in range(self.n_rows):
            for j in range(self.n_cols):
                if self.cells[i][j]==self.white:
                    color_white+=1
                elif self.cells[i][j]==self.black:
                    color_black+=1
                else:
                    color_white+=0
                    color_black+=0
            
        if color_white>color_black:
            print('winner:white')
        elif color_white==color_black:
            print('on drow')
        else:
            print('winner:black')
            
    def show_index(self):
        def index_to_axis(index):
            r=int(index/8)
            c=index%8
            return [r,c]
        index_list=list(np.arange(0,self.n_rows*self.n_cols))
        axis_list=[]
        
        for i in range(0,self.n_rows*self.n_cols,self.n_rows):
            ind=index_list[i:i+self.n_rows]
            bb=[]
            for j in range(len(ind)):
                bb.append(index_to_axis(ind[j]))
            axis_list.append(bb)
            
        for i in range(self.n_rows):
            print(axis_list[i])
            
    def get_enables(self,color):
        """置ける位置のリストを返す関数"""
        result=[]
        enable_actions=np.arange(0,self.n_rows*self.n_cols)
        for action in enable_actions:
            r,c=self.index2axis(action)
            if self.cells[r][c]==self.blank:
                if len(self.possible)>0:
                    result.append([r,c])
        return result
            
            
            
    def index2axis(self,index):
        r=int(index/8)
        c=index%8
        return r,c
            


#オセロゲーム
count=0
max_number=2 #64
player=2
osero=osero()
while count<max_number:
    print('==%d step=='%count)
    osero.show_board()
    print(osero.cells)
    print('==winner determination==')
    osero.winner()
    print('==player==')
    print('white'if player==1 else 'black')
    index=list(map(int,input().split()))
    osero.flip_able_man(index,player)
    osero.flip()
    print(osero.End(player))
    player=osero.player_change(player)
    count+=1
    

==0 step==
[['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '○' '●' '*' '*' '*']
 ['*' '*' '*' '●' '○' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']]
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  2.  0.  0.  0.]
 [ 0.  0.  0.  2.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
==winner determination==
on drow
==player==
black
2 3
False
==1 step==
[['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '●' '*' '*' '*' '*']
 ['*' '*' '*' '●' '●' '*' '*' '*']
 ['*' '*' '*' '●' '○' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']]
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.

In [ ]:
## print('==%d step=='%count)
osero.show_board()
print('==winner determination==')
osero.winner()
print('player:','white'if player==1 else 'black')
osero.flip_able_man([2,2],player)
osero.flip()
player=osero.player_change(player)
count+=1

In [34]:
print('==%d step=='%count)
osero.show_board()
print('==winner determination==')
osero.winner()
print('player:','white'if player==1 else 'black')

==2 step==
[['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '○' '●' '*' '*' '*' '*']
 ['*' '*' '*' '○' '●' '*' '*' '*']
 ['*' '*' '*' '●' '○' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']]
==winner determination==
on drow
player: black


In [35]:
osero.flip_able_man([5,4],player)
osero.flip()
player=osero.player_change(player)
count+=1

In [36]:
print('==%d step=='%count)
osero.show_board()
print('==winner determination==')
osero.winner()
print('player:','white'if player==1 else 'black')

==3 step==
[['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '○' '●' '*' '*' '*' '*']
 ['*' '*' '*' '○' '●' '*' '*' '*']
 ['*' '*' '*' '●' '●' '*' '*' '*']
 ['*' '*' '*' '*' '●' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']]
==winner determination==
winner:black
player: white


In [37]:
osero.flip_able_man([3,5],player)
osero.flip()
player=osero.player_change(player)
count+=1

In [38]:
print('==%d step=='%count)
osero.show_board()
print('==winner determination==')
osero.winner()
print('player:','white'if player==1 else 'black')

==4 step==
[['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '○' '●' '*' '*' '*' '*']
 ['*' '*' '*' '○' '○' '○' '*' '*']
 ['*' '*' '*' '●' '●' '*' '*' '*']
 ['*' '*' '*' '*' '●' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']]
==winner determination==
on drow
player: black


In [39]:
osero.flip_able_man([3,6],player)
osero.flip()
player=osero.player_change(player)
count+=1

In [40]:
print('==%d step=='%count)
osero.show_board()
print('==winner determination==')
osero.winner()
print('player:','white'if player==1 else 'black')

==5 step==
[['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '○' '●' '*' '*' '*' '*']
 ['*' '*' '*' '○' '○' '○' '●' '*']
 ['*' '*' '*' '●' '●' '*' '*' '*']
 ['*' '*' '*' '*' '●' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*']]
==winner determination==
winner:black
player: white
